name: Java CI

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: action/checkout@3

      - name: Set up JDK
        uses: action/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Run and Build Maven
        run: mvn clean verify
